package driver

import "time"

// SmartEvent represents a structured event generated by parsing CLI output.
type SmartEvent struct {
	Kind    string   `json:"kind"`    // "question", "idle", "progress", "claude_confirm"
	Options []string `json:"options"` // ["yes", "no"] or ["1", "2", "esc"]
	Prompt  string   `json:"prompt"`  // Original prompt text
}

// Message represents a parsed message from the conversation.
type Message struct {
	Timestamp time.Time `json:"timestamp"`
	Type      string    `json:"type"`    // "user_input", "claude_response", "claude_action", "action_result", "command_output", "agent_interrupted"
	Content   string    `json:"content"` // The message content
}

// ParseResult contains the result of parsing PTY output.
type ParseResult struct {
	RawData     []byte
	SmartEvents []SmartEvent
	Messages    []Message // Parsed conversation messages
}

// InputAction represents an action to send to the PTY
type InputAction struct {
	Type    string `json:"type"`    // "text", "key", "confirm", "cancel"
	Content string `json:"content"` // Text content or key name
}

// Common key codes for PTY input
const (
	KeyEnter     = "\r"
	KeyEscape    = "\x1b"
	KeyCtrlC     = "\x03"
	KeyCtrlD     = "\x04"
	KeyBackspace = "\x7f"
	KeyTab       = "\t"
	KeyUp        = "\x1b[A"
	KeyDown      = "\x1b[B"
	KeyRight     = "\x1b[C"
	KeyLeft      = "\x1b[D"
)

// AgentDriver is an interface for parsing CLI output and generating smart events.
type AgentDriver interface {
	// Name returns the name of the driver.
	Name() string

	// Parse processes a chunk of PTY output and returns parsed results.
	// It returns the raw data along with any detected smart events.
	Parse(chunk []byte) (*ParseResult, error)

	// FormatInput formats an input action into bytes to send to PTY.
	// This handles special keys, confirmations, and text input.
	FormatInput(action InputAction) []byte

	// RespondToEvent generates the appropriate input for a SmartEvent response.
	// For example, responding "yes" to a (y/n) question or selecting option 1.
	RespondToEvent(event SmartEvent, response string) []byte
}

// GenericDriver is a pass-through driver that doesn't perform any parsing.
// It simply returns the raw data without generating any smart events.
type GenericDriver struct{}

// NewGenericDriver creates a new GenericDriver instance.
func NewGenericDriver() *GenericDriver {
	return &GenericDriver{}
}

// Name returns the name of the driver.
func (d *GenericDriver) Name() string {
	return "generic"
}

// Parse returns the raw data without any parsing or smart event generation.
func (d *GenericDriver) Parse(chunk []byte) (*ParseResult, error) {
	return &ParseResult{
		RawData:     chunk,
		SmartEvents: nil,
	}, nil
}

// FormatInput formats an input action into bytes for PTY.
func (d *GenericDriver) FormatInput(action InputAction) []byte {
	switch action.Type {
	case "text":
		return []byte(action.Content)
	case "key":
		return formatKey(action.Content)
	case "confirm":
		return []byte(action.Content + KeyEnter)
	case "cancel":
		return []byte(KeyEscape)
	default:
		return []byte(action.Content)
	}
}

// RespondToEvent generates input for a SmartEvent response.
func (d *GenericDriver) RespondToEvent(event SmartEvent, response string) []byte {
	// Generic driver just sends the response as-is with Enter
	return []byte(response + KeyEnter)
}

// formatKey converts a key name to its escape sequence
func formatKey(keyName string) []byte {
	switch keyName {
	case "enter":
		return []byte(KeyEnter)
	case "escape", "esc":
		return []byte(KeyEscape)
	case "ctrl+c":
		return []byte(KeyCtrlC)
	case "ctrl+d":
		return []byte(KeyCtrlD)
	case "backspace":
		return []byte(KeyBackspace)
	case "tab":
		return []byte(KeyTab)
	case "up":
		return []byte(KeyUp)
	case "down":
		return []byte(KeyDown)
	case "left":
		return []byte(KeyLeft)
	case "right":
		return []byte(KeyRight)
	default:
		return []byte(keyName)
	}
}
