package driver

import "time"

// SmartEvent represents a structured event generated by parsing CLI output.
type SmartEvent struct {
	Kind    string   `json:"kind"`    // "question", "idle", "progress", "claude_confirm"
	Options []string `json:"options"` // ["yes", "no"] or ["1", "2", "esc"]
	Prompt  string   `json:"prompt"`  // Original prompt text
}

// Message represents a parsed message from the conversation.
type Message struct {
	Timestamp time.Time `json:"timestamp"`
	Type      string    `json:"type"`    // "user_input", "claude_response", "claude_action", "action_result", "command_output", "agent_interrupted"
	Content   string    `json:"content"` // The message content
}

// ParseResult contains the result of parsing PTY output.
type ParseResult struct {
	RawData     []byte
	SmartEvents []SmartEvent
	Messages    []Message // Parsed conversation messages
}

// AgentDriver is an interface for parsing CLI output and generating smart events.
type AgentDriver interface {
	// Name returns the name of the driver.
	Name() string

	// Parse processes a chunk of PTY output and returns parsed results.
	// It returns the raw data along with any detected smart events.
	Parse(chunk []byte) (*ParseResult, error)
}

// GenericDriver is a pass-through driver that doesn't perform any parsing.
// It simply returns the raw data without generating any smart events.
type GenericDriver struct{}

// NewGenericDriver creates a new GenericDriver instance.
func NewGenericDriver() *GenericDriver {
	return &GenericDriver{}
}

// Name returns the name of the driver.
func (d *GenericDriver) Name() string {
	return "generic"
}

// Parse returns the raw data without any parsing or smart event generation.
func (d *GenericDriver) Parse(chunk []byte) (*ParseResult, error) {
	return &ParseResult{
		RawData:     chunk,
		SmartEvents: nil,
	}, nil
}
